# Generated by Django 3.2.3 on 2022-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.IntegerField(help_text='Enter what week you would like to add scores for (between 1-10)'),
        ),
    ]
