# Generated by Django 3.2.3 on 2022-09-23 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challange', '0005_auto_20220923_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challange.customer'),
        ),
    ]
