# Generated by Django 3.2.3 on 2022-07-28 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_rename_foods_cat_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='food',
            new_name='foods',
        ),
        migrations.AlterField(
            model_name='cat',
            name='nickname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')]),
        ),
    ]
