# Generated by Django 3.2.3 on 2022-08-03 01:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20220728_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(2, 'Joke must be more than 5 characters')])),
                ('creator', models.CharField(max_length=300)),
                ('cats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
            ],
        ),
    ]
